# Generated by Django 4.2.2 on 2023-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='mode2',
            name='pole4',
            field=models.ManyToManyField(to='testapp.mode1'),
        ),
    ]
