# Generated by Django 4.2.2 on 2023-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limk', models.TextField(verbose_name='Ссылка')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
