# Generated by Django 4.2.2 on 2023-06-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mebel',
            old_name='limk',
            new_name='link',
        ),
    ]
