# Generated by Django 4.2.2 on 2023-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_rename_limk_mebel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
    ]
