# Generated by Django 4.2.2 on 2023-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_mebel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Цена'),
        ),
    ]
